# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kampKaydi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(997, 675)
        font = QtGui.QFont()
        font.setUnderline(False)
        MainWindow.setFont(font)
        MainWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(650, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(580, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(570, 100, 281, 281))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("Jade Distribütör Kamp.jpeg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(690, 60, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(580, 390, 131, 91))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("BeedemyLogo.jpeg"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(720, 390, 131, 91))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("BeluventaLogo.jpeg"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 10, 431, 441))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.cmbKampAdi = QtWidgets.QComboBox(self.layoutWidget)
        self.cmbKampAdi.setObjectName("cmbKampAdi")
        self.cmbKampAdi.addItem("")
        self.horizontalLayout_10.addWidget(self.cmbKampAdi)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lneAd = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneAd.setObjectName("lneAd")
        self.horizontalLayout.addWidget(self.lneAd)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.lneSoyad = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneSoyad.setObjectName("lneSoyad")
        self.horizontalLayout_2.addWidget(self.lneSoyad)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.lneTC = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneTC.setInputMask("")
        self.lneTC.setMaxLength(11)
        self.lneTC.setObjectName("lneTC")
        self.horizontalLayout_3.addWidget(self.lneTC)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.cmbCinsiyet = QtWidgets.QComboBox(self.layoutWidget)
        self.cmbCinsiyet.setObjectName("cmbCinsiyet")
        self.cmbCinsiyet.addItem("")
        self.cmbCinsiyet.addItem("")
        self.horizontalLayout_4.addWidget(self.cmbCinsiyet)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.cwDTarihi = QtWidgets.QCalendarWidget(self.layoutWidget)
        self.cwDTarihi.setObjectName("cwDTarihi")
        self.verticalLayout.addWidget(self.cwDTarihi)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.chkOdeme = QtWidgets.QCheckBox(self.layoutWidget)
        self.chkOdeme.setObjectName("chkOdeme")
        self.horizontalLayout_6.addWidget(self.chkOdeme)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.cmbOdenenKisi = QtWidgets.QComboBox(self.layoutWidget)
        self.cmbOdenenKisi.setObjectName("cmbOdenenKisi")
        self.cmbOdenenKisi.addItem("")
        self.cmbOdenenKisi.addItem("")
        self.cmbOdenenKisi.addItem("")
        self.cmbOdenenKisi.addItem("")
        self.cmbOdenenKisi.addItem("")
        self.cmbOdenenKisi.addItem("")
        self.cmbOdenenKisi.addItem("")
        self.cmbOdenenKisi.addItem("")
        self.horizontalLayout_7.addWidget(self.cmbOdenenKisi)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.lneHesKodu = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneHesKodu.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.lneHesKodu.setFont(font)
        self.lneHesKodu.setStatusTip("")
        self.lneHesKodu.setMaxLength(11)
        self.lneHesKodu.setCursorPosition(11)
        self.lneHesKodu.setPlaceholderText("")
        self.lneHesKodu.setObjectName("lneHesKodu")
        self.horizontalLayout_8.addWidget(self.lneHesKodu)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 460, 482, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btnKaydet = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnKaydet.setFont(font)
        self.btnKaydet.setObjectName("btnKaydet")
        self.horizontalLayout_9.addWidget(self.btnKaydet)
        self.btnAra = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnAra.setFont(font)
        self.btnAra.setObjectName("btnAra")
        self.horizontalLayout_9.addWidget(self.btnAra)
        self.btnGuncelle = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnGuncelle.setFont(font)
        self.btnGuncelle.setObjectName("btnGuncelle")
        self.horizontalLayout_9.addWidget(self.btnGuncelle)
        self.btnListele = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnListele.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnListele.setFont(font)
        self.btnListele.setObjectName("btnListele")
        self.horizontalLayout_9.addWidget(self.btnListele)
        self.btnSil = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnSil.setFont(font)
        self.btnSil.setObjectName("btnSil")
        self.horizontalLayout_9.addWidget(self.btnSil)
        self.tblwkampBilgi = QtWidgets.QTableWidget(self.centralwidget)
        self.tblwkampBilgi.setGeometry(QtCore.QRect(0, 500, 1051, 221))
        self.tblwkampBilgi.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tblwkampBilgi.setAutoScrollMargin(16)
        self.tblwkampBilgi.setShowGrid(True)
        self.tblwkampBilgi.setGridStyle(QtCore.Qt.SolidLine)
        self.tblwkampBilgi.setWordWrap(True)
        self.tblwkampBilgi.setCornerButtonEnabled(True)
        self.tblwkampBilgi.setRowCount(100)
        self.tblwkampBilgi.setColumnCount(10)
        self.tblwkampBilgi.setObjectName("tblwkampBilgi")
        self.tblwkampBilgi.horizontalHeader().setDefaultSectionSize(100)
        self.tblwkampBilgi.horizontalHeader().setMinimumSectionSize(39)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 997, 21))
        self.menubar.setObjectName("menubar")
        self.menuEGITIM = QtWidgets.QMenu(self.menubar)
        self.menuEGITIM.setObjectName("menuEGITIM")
        self.menuTOPLANTI = QtWidgets.QMenu(self.menubar)
        self.menuTOPLANTI.setObjectName("menuTOPLANTI")
        self.menuKAMP = QtWidgets.QMenu(self.menubar)
        self.menuKAMP.setObjectName("menuKAMP")
        self.menuKamp_Kazananlar = QtWidgets.QMenu(self.menuKAMP)
        self.menuKamp_Kazananlar.setObjectName("menuKamp_Kazananlar")
        self.menuAnasayfa = QtWidgets.QMenu(self.menubar)
        self.menuAnasayfa.setObjectName("menuAnasayfa")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHak_nda = QtWidgets.QAction(MainWindow)
        self.actionHak_nda.setObjectName("actionHak_nda")
        self.actionYakla_an_Kamplar = QtWidgets.QAction(MainWindow)
        self.actionYakla_an_Kamplar.setObjectName("actionYakla_an_Kamplar")
        self.actionKamp_Kayd = QtWidgets.QAction(MainWindow)
        self.actionKamp_Kayd.setObjectName("actionKamp_Kayd")
        self.actionKamp_Gere_leri = QtWidgets.QAction(MainWindow)
        self.actionKamp_Gere_leri.setObjectName("actionKamp_Gere_leri")
        self.actionKamp_Fotograflar = QtWidgets.QAction(MainWindow)
        self.actionKamp_Fotograflar.setObjectName("actionKamp_Fotograflar")
        self.actionEkip = QtWidgets.QAction(MainWindow)
        self.actionEkip.setObjectName("actionEkip")
        self.actionKisisel = QtWidgets.QAction(MainWindow)
        self.actionKisisel.setObjectName("actionKisisel")
        self.actionKariyer_E_itimleri = QtWidgets.QAction(MainWindow)
        self.actionKariyer_E_itimleri.setObjectName("actionKariyer_E_itimleri")
        self.actionHaftal_k_Toplant_lar = QtWidgets.QAction(MainWindow)
        self.actionHaftal_k_Toplant_lar.setObjectName("actionHaftal_k_Toplant_lar")
        self.actionD_nemsel_Toplant_lar = QtWidgets.QAction(MainWindow)
        self.actionD_nemsel_Toplant_lar.setObjectName("actionD_nemsel_Toplant_lar")
        self.menuEGITIM.addAction(self.actionKariyer_E_itimleri)
        self.menuTOPLANTI.addAction(self.actionHaftal_k_Toplant_lar)
        self.menuTOPLANTI.addAction(self.actionD_nemsel_Toplant_lar)
        self.menuKamp_Kazananlar.addAction(self.actionEkip)
        self.menuKamp_Kazananlar.addAction(self.actionKisisel)
        self.menuKAMP.addAction(self.actionHak_nda)
        self.menuKAMP.addAction(self.actionYakla_an_Kamplar)
        self.menuKAMP.addAction(self.actionKamp_Kayd)
        self.menuKAMP.addAction(self.actionKamp_Gere_leri)
        self.menuKAMP.addAction(self.actionKamp_Fotograflar)
        self.menuKAMP.addAction(self.menuKamp_Kazananlar.menuAction())
        self.menubar.addAction(self.menuAnasayfa.menuAction())
        self.menubar.addAction(self.menuEGITIM.menuAction())
        self.menubar.addAction(self.menuTOPLANTI.menuAction())
        self.menubar.addAction(self.menuKAMP.menuAction())

        self.retranslateUi(MainWindow)
        self.cmbKampAdi.setCurrentIndex(-1)
        self.cmbCinsiyet.setCurrentIndex(-1)
        self.cmbOdenenKisi.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", " Kamp Kaydı"))
        self.label_12.setText(_translate("MainWindow", "Kampın Tarihi:"))
        self.label_13.setText(_translate("MainWindow", "28-29-30 Mayıs 2021"))
        self.label_11.setText(_translate("MainWindow", "Kampın Adı:"))
        self.cmbKampAdi.setItemText(0, _translate("MainWindow", "JADE DISTRIBUTORS CAMP"))
        self.label.setText(_translate("MainWindow", "Adınız:"))
        self.label_2.setText(_translate("MainWindow", "Soyadınız:"))
        self.label_3.setText(_translate("MainWindow", "TC Kimlik No:"))
        self.lneTC.setPlaceholderText(_translate("MainWindow", "Arama için TC nizi giriniz."))
        self.label_4.setText(_translate("MainWindow", "Cinsiyet:"))
        self.cmbCinsiyet.setItemText(0, _translate("MainWindow", "Erkek"))
        self.cmbCinsiyet.setItemText(1, _translate("MainWindow", "Kadın"))
        self.label_6.setText(_translate("MainWindow", "Doğum Tarihi:"))
        self.label_7.setText(_translate("MainWindow", "Dekont:"))
        self.chkOdeme.setText(_translate("MainWindow", "Odendi"))
        self.label_8.setText(_translate("MainWindow", "Ödeme Yapılan Yetkili:"))
        self.cmbOdenenKisi.setItemText(0, _translate("MainWindow", "Mesut Geç"))
        self.cmbOdenenKisi.setItemText(1, _translate("MainWindow", "Yunus Emre Tank"))
        self.cmbOdenenKisi.setItemText(2, _translate("MainWindow", "Murat Çelik"))
        self.cmbOdenenKisi.setItemText(3, _translate("MainWindow", "Cihad Kaymaz"))
        self.cmbOdenenKisi.setItemText(4, _translate("MainWindow", "Ali Yiğit Aydınalp"))
        self.cmbOdenenKisi.setItemText(5, _translate("MainWindow", "Mehmet Ali Yıldız"))
        self.cmbOdenenKisi.setItemText(6, _translate("MainWindow", "Mikail Erdil"))
        self.cmbOdenenKisi.setItemText(7, _translate("MainWindow", "Mithat Turhan"))
        self.label_10.setText(_translate("MainWindow", "Hes Kodu:"))
        self.lneHesKodu.setInputMask(_translate("MainWindow", "NNNN-NNNNNN"))
        self.lneHesKodu.setText(_translate("MainWindow", "-"))
        self.btnKaydet.setText(_translate("MainWindow", "Kaydet"))
        self.btnAra.setText(_translate("MainWindow", "Ara"))
        self.btnGuncelle.setText(_translate("MainWindow", "Güncelle"))
        self.btnListele.setText(_translate("MainWindow", "Listele"))
        self.btnSil.setText(_translate("MainWindow", "Sil"))
        self.menuEGITIM.setTitle(_translate("MainWindow", "EGITIM"))
        self.menuTOPLANTI.setTitle(_translate("MainWindow", "TOPLANTI"))
        self.menuKAMP.setTitle(_translate("MainWindow", "KAMP"))
        self.menuKamp_Kazananlar.setTitle(_translate("MainWindow", "Kamp Kazananları"))
        self.menuAnasayfa.setTitle(_translate("MainWindow", "Anasayfa"))
        self.actionHak_nda.setText(_translate("MainWindow", "Hakıında"))
        self.actionYakla_an_Kamplar.setText(_translate("MainWindow", "Yaklaşan Kamplar"))
        self.actionKamp_Kayd.setText(_translate("MainWindow", "Kamp Kaydı"))
        self.actionKamp_Gere_leri.setText(_translate("MainWindow", "Kamp Gereçleri"))
        self.actionKamp_Fotograflar.setText(_translate("MainWindow", "Kamp Fotografları"))
        self.actionEkip.setText(_translate("MainWindow", "Ekip"))
        self.actionKisisel.setText(_translate("MainWindow", "Kisisel"))
        self.actionKariyer_E_itimleri.setText(_translate("MainWindow", "Kariyer Eğitimleri"))
        self.actionHaftal_k_Toplant_lar.setText(_translate("MainWindow", "Haftalık Toplantılar"))
        self.actionD_nemsel_Toplant_lar.setText(_translate("MainWindow", "Dönemsel Toplantılar"))

